---
version: "3.7"
services:

  # DATABASES
  balls-sql:
    image: mariadb:10.8.3
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - balls-sql-data:/var/lib/mysql
    ports:
      - "33060:3306"
    container_name: balls-sql
    environment:
      MYSQL_ROOT_PASSWORD: "Sitius4Lyfe"
      MYSQL_DATABASE: "balls_db"
      
volumes:
  balls-sql-data:
    name: balls-sql-data