spring.datasource.url=jdbc:mariadb://localhost:33060/space_db
spring.datasource.username=root
spring.datasource.password=Sitius4Lyfe
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
